// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UA6NjucqQu8dI6-AmnpQMWwzF6jAEck',
    appId: '1:792277291500:web:9349e42fa7e40e671e30c9',
    messagingSenderId: '792277291500',
    projectId: 'tictactoe-abs',
    authDomain: 'tictactoe-abs.firebaseapp.com',
    storageBucket: 'tictactoe-abs.firebasestorage.app',
    measurementId: 'G-V2LBMBBS00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NE7LEdn8VFKBfmV3IdDDuIk1VOksZwI',
    appId: '1:792277291500:android:39bec678639d36861e30c9',
    messagingSenderId: '792277291500',
    projectId: 'tictactoe-abs',
    storageBucket: 'tictactoe-abs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaHrmqnC6rHrPUnhSIAFfcbeNJ8l3hWWU',
    appId: '1:792277291500:ios:cb699c516b5429a91e30c9',
    messagingSenderId: '792277291500',
    projectId: 'tictactoe-abs',
    storageBucket: 'tictactoe-abs.firebasestorage.app',
    iosBundleId: 'com.abhishek.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaHrmqnC6rHrPUnhSIAFfcbeNJ8l3hWWU',
    appId: '1:792277291500:ios:cb699c516b5429a91e30c9',
    messagingSenderId: '792277291500',
    projectId: 'tictactoe-abs',
    storageBucket: 'tictactoe-abs.firebasestorage.app',
    iosBundleId: 'com.abhishek.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_UA6NjucqQu8dI6-AmnpQMWwzF6jAEck',
    appId: '1:792277291500:web:5072e8788d1e97391e30c9',
    messagingSenderId: '792277291500',
    projectId: 'tictactoe-abs',
    authDomain: 'tictactoe-abs.firebaseapp.com',
    storageBucket: 'tictactoe-abs.firebasestorage.app',
    measurementId: 'G-YT7BYMT5R9',
  );

}